### ISSUE TITLE
Remove ImagePartTypeInfo

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/Open-XML-SDK#1424]
In a recent change @tomjebo made, we consolidated many of the methods for adding parts. Looks like https://github.com/dotnet/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml/Packaging/ImagePartTypeInfo.cs was left - it and its calling method should be removed

**Comment by tomjebo** [comment]
@twsouthwick actually, I left that intentionally because it's used by the `AddImagePart(MainDocumentPart, extension)` variant in `ImagePartTypeExtensions.cs`. I don't know the reason why that method (`AddImagePart`) was introduced so I left it alone. Do we no longer need that? It does seem a bit odd to have that overload for just the MainDocumentPart and not other parents.

Looks like that method was added in #1082 by @JaimeStill

**Comment by twsouthwick** [comment]
The problem is that now `mainPart.AddImagePart("some string")` will have two competing overloads.

**Comment by tomjebo** [comment]
that's true. Then I agree, we should remove it. The new way with PartTypeInfo is better.

**Comment by twsouthwick** [comment]
@JaimeStill I want to make sure we don't break you - can we rename this method you added for v3?

**Comment by JaimeStill** [comment]
Please do, this was purely something that I found during R&D with this project.
