### ISSUE TITLE
Is Storm-0978/CVE-2023-36884 affecting this library?

### ISSUE THREAD

**Issue by Xerillio** [dotnet/Open-XML-SDK#1494]
**Describe the bug**
On our project we're using `DocumentFormat.OpenXml` to convert OOXML documents to HTML (`WmlToHtmlConverter.ConvertToHtml(WordprocessingDocument, WmlToHtmlConverterSettings)`). Given the newly found [CVE-2023-36884 vulnerability](https://www.microsoft.com/en-us/security/blog/2023/07/11/storm-0978-attacks-reveal-financial-and-espionage-motives/) we've been trying to figure out if this library is affected by it. However, I can't seem to find details about how macros and remote content (altChunk) is loaded (if at all). Can you tell us if we need to take any precautions or if this library is safe from this vulnerability?

**Server (please complete the following information):**
 - OS: Windows
 - .NET Target:.NET Framework 4.7.2
 - DocumentFormat.OpenXml Version: 2.20.0

**Comment by tomjebo** [comment]
Hi @Xerillio, 
 
Thanks for checking with us on this CVE. We have reviewed the CVE report with the Office security team and find that the Open XML SDK should not be affected by these attacks due to the fact that it does not execute OLE controls or process alt chunk remote content. If you disagree or have further questions or concerns, please reopen and let us know.
