### ISSUE TITLE
SpacingBetweenLines - validation errors.

### ISSUE THREAD

**Issue by Jackhammer88** [dotnet/Open-XML-SDK#1612]
### Describe the bug
When generating DOCX files in .NET 8, using SpacingBetweenLines in paragraph properties within tables leads to validation errors in OpenXML SDK 2.5 Productivity Tool. The issue seems to arise specifically when the SpacingBetweenLines object is used with certain properties.

### To Reproduce

1. Create a DOCX file in .NET 8 using DocumentFormat.OpenXml.
2. Define a paragraph within a table and set SpacingBetweenLines as follows:

```csharp
SpacingBetweenLines spacingBetweenLines = new ()
{
    Before = SpacingBefore.ToString(),
    After = SpacingAfter.ToString(),
    Line = SpacingLine.ToString(),
    LineRule = LineSpacingRuleValues.Auto
};
```

3. Validate the generated DOCX file using OpenXML SDK 2.5 Productivity Tool.
4. Observe the validation error related to the paragraph with SpacingBetweenLines.

Example of the generated paragraph XML:
```xml
<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:pPr>
    <w:jc w:val="left" />
    <w:spacing w:before="160" w:after="160" w:line="240" w:lineRule="auto" />
    <w:rPr>
      <w:rFonts w:ascii="Liberation Mono" w:hAnsi="Liberation Mono" w:cs="Liberation Mono" />
      <w:sz w:val="28" />
      <w:szCs w:val="28" />
      <w:lang w:val="en-US" />
    </w:rPr>
  </w:pPr>
  <w:r>
    <w:rPr>
      <w:rFonts w:ascii="Liberation Mono" w:hAnsi="Liberation Mono" />
      <w:sz w:val="28" />
      <w:szCs w:val="28" />
    </w:rPr>
    <w:t xml:space="preserve">merged</w:t>
  </w:r>
</w:p>
```
### Observed behavior
Validation error in OpenXML SDK 2.5 Productivity Tool when paragraphs with **SpacingBetweenLines** are present. The error suggests an issue with the paragraph's spacing configuration.

### Expected behavior
No validation errors should occur when SpacingBetweenLines is used as per the documentation and standards of OpenXML. The paragraphs should conform to the OpenXML specification without causing validation issues.

### Desktop (please complete the following information):

OS:Ubuntu 22.04
Office version [doesn't matter, validated in oxml sdk 2.5 productivity tool in wine]
.NET Target: [.NET 8]
DocumentFormat.OpenXml Version: 3.0.0
Additional context
The issue appears to be related to the handling of SpacingBetweenLines in paragraphs within tables. Notably, the ECMA-376 specification does not seem to include such parameters in the description of spacing for paragraphs, as shown in the example from section 17.3.2.35:
```xml
<w:rPr>
  <w:spacing w:val="200"/>
</w:rPr>
```
This discrepancy might be contributing to the validation error observed.
![image](https://github.com/dotnet/Open-XML-SDK/assets/19895415/bf40dcf3-1051-4879-9e99-ad8cf65e1564)

**Comment by tomjebo** [comment]
Hi @Jackhammer88, 

The problem here should be the order of pPr properties. If you create the new `SpacingBetweenLines` object and append it to the `ParagraphProperties` object, you have to be careful to append it in the correct order relative to other properties. Sequences have order and the validation error is specifically calling out that the `w:spacing` element is placed incorrectly in the sequence. 

For example, the following code will create the properties in the correct order: 

```csharp
    Paragraph para = body.AppendChild(new Paragraph());
    SpacingBetweenLines spacingBetweenLines = new()
    {
        Before = "80",
        After = "240",
        Line = "276",
        LineRule = LineSpacingRuleValues.Auto
    };

    para.ParagraphProperties = new ParagraphProperties();
    para.ParagraphProperties.AppendChild(spacingBetweenLines);
    para.ParagraphProperties.AppendChild(new Justification() { Val = JustificationValues.End });
```
And will result in the following XML: 

```xml
    <w:p>
      <w:pPr>
        <w:spacing w:before="80" w:after="240" w:line="276" w:lineRule="auto"/>
        <w:jc w:val="end"/>
      </w:pPr>
      <w:r>
        <w:t>Hello World</w:t>
      </w:r>
    </w:p>
```
But switching these two lines: 
```csharp
    para.ParagraphProperties.AppendChild(new Justification() { Val = JustificationValues.End });
    para.ParagraphProperties.AppendChild(spacingBetweenLines);
``` 

Will result in the wrong order and the validation error you're seeing.

**Comment by Jackhammer88** [comment]
Thanks. It was really helpful.

**Comment by tomjebo** [comment]
@Jackhammer88 I should also have added here that using AppendChild will not take into account the sequence of the child nodes under the parent object. If instead you use AddChild, this should respect the sequence order without having to do any extra processing in your own code. For example, instead of my code above, you could use: 

```csharp
    Paragraph para = body.AppendChild(new Paragraph());
    SpacingBetweenLines spacingBetweenLines = new()
    {
        Before = "80",
        After = "240",
        Line = "276",
        LineRule = LineSpacingRuleValues.Auto
    };

    para.ParagraphProperties = new ParagraphProperties();
    para.ParagraphProperties.AddChild(new Justification() { Val = JustificationValues.End });
    para.ParagraphProperties.AddChild(spacingBetweenLines);
```

Regardless of the fact that the Justification child is added first, the SpacingBetweenLines child will be added correctly before the Justification child.
