### ISSUE TITLE
Rich text support in power point

### ISSUE THREAD

**Issue by ManikaSood** [dotnet/Open-XML-SDK#1791]
Hi Team, 

We are currently utilizing OpenXML SDK 2.5 and DocumentFormat.OpenXml (version 2.19.0) within our .NET application (C#) to generate reports in the PPTX format. Previously, our data source for the reports was plain text in JSON format. As part of an enhancement, we are now incorporating rich text into the JSON data source.

However, we are encountering an issue: when generating reports with our existing implementation—where we use the "Text" => "Run" => "Paragraph" => "TextBody" control to display text—the generated report displays the raw HTML tags instead of interpreting them.

For instance, if we pass `<div><strong>test data</strong></div>` in our source JSON, the output should appear in bold as follows: **test data**. 
Currently, the output includes the HTML tags as plain text: `<div><strong>test data</strong></div>`, rather than rendering the HTML correctly.

**So just want to check if there is any way to handle the rich text in the Power point format so that the corresponding html tags will do their respective function in generated report.**

We would appreciate guidance on how to handle rich text in the PowerPoint format so that the HTML tags are properly interpreted and rendered in the generated PPTX report.

Your assistance in achieving the desired output would be greatly valued.

Thanks in advance.
Manika Sood

**Comment by mikeebowen** [comment]
Hi @ManikaSood, 

I am closing this, because PowerPoint cannot render HTML the way you describe, [see this answers.microsoft post](https://answers.microsoft.com/en-us/msoffice/forum/all/importing-html-objects-into-powerpoint/43ffc6ec-87ed-47c5-b4c0-99b76945a975#LastReply), so what you describe can't work.

You will need to use determine the style in your application and then use the `DocumentFormat.OpenXml.Drawing.RunProperties` class or another method to style the text.
